NFG-83 Update husky with default branches

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,15 +1,15 @@
-#!/bin/sh
-# This hook checks that branches are named according to the convention.
-
+# This hook checks that branches are named according to the updated convention.
 current_branch=$(git rev-parse --abbrev-ref HEAD)
-branch_regex="^(feature|bugfix|hotfix|release)/NFG-[0-9]+-.+$"
+branch_regex="^(development|staging|testing|production|(^(feature|bugfix|hotfix|release)/NFG-[0-9]+-.+$)$)"
 
-if ! echo "$current_branch" | grep -Eq "$branch_regex"; then
-  echo "Error: Branch name '$current_branch' does not follow the naming convention."
-  echo "Please rename your branch to follow the convention: (feature|bugfix|hotfix|release)/NFG-123-description."
-  exit 1
+if ! echo "$current_branch" | grep -qE "$branch_regex"; then
+    echo "Error: Branch name '$current_branch' does not follow the naming convention."
+    echo "Please rename your branch to follow the convention: "
+    echo " - For environment branches: (development|staging|testing|production)"
+    echo " - For feature branches: (feature|bugfix|hotfix|release)/NFG-<issue-number>-description."
+    exit 1
 fi
 
-# Lint staged files
+# Format staged files using Prettier
 prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown
 git update-index --again
